#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Kanon Ode <s24c1028wf@s.chibakoudai.jp>
# SPDX-License-Identifier:BSD-3-Clause

import sys

seireki = int(sys.stdin.read())

if seireki >= 2019:
    gengo = "令和"
    year_num = seireki - 2018
elif seireki >= 1989:
    gengo = "平成"
    year_num = seireki - 1988
elif seireki >= 1926:
    gengo = "昭和"
    year_num = seireki - 1925
elif seireki >= 1912:
    gengo = "大正"
    year_num = seireki - 1911
elif seireki >= 1868:
    gengo = "明治"
    year_num = seireki - 1867
else:
    gengo = "明治より前"
    year_num = 0

if gengo == "明治より前":
    print("明治より前の年代です。ググりましょう")
elif year_num == 1:
    print(f"{gengo}元年")
else:
    print(f"{gengo}{year_num}年")
